spring:
  application:
    name: service-client
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  task:
    execution:
      thread-name-prefix: autohost-task-
      pool:
        core-size: 2
        max-size: 200
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: mail-receiver-
      pool:
        size: 2
  cache:
    jcache:
      config: classpath:ehcache.xml
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 30MB
logging:
  level:
    com.telegrambot.marketplace: TRACE
    org:
      springframework: DEBUG
      flywaydb: DEBUG
      hibernate: DEBUG
aws:
  s3:
    publicEndpoint: https://104.194.214.119:9000
    privateEndpoint: http://104.194.214.119:9000
    bucketName: productportion
    stuffPlaceFolder: productPortion
    accessKey: B072BVXCPsnfXNlr9HaS
    secretKey: e5hX9a7WSDFB5GPa9AlVA53HxHFdJBFdDCGTAxpG
bot:
  name: ${BOT_NAME:BotName}
  token: ${BOT_TOKEN:BotToken}
filesize:
  photo: 3145728
  video: 15728640
server:
  port: 8080
