stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-22-alpine
  script:
    - mvn clean install
  artifacts:
    paths:
      - service-client/target/service-client-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
  script:
    - scp service-client/target/service-client-0.0.1-SNAPSHOT.jar $REMOTE_USER@$REMOTE_HOST:/bot
    - ssh $REMOTE_USER@$REMOTE_HOST 'pkill -f "java -jar service-client-0.0.1-SNAPSHOT.jar" || true'
    - ssh $REMOTE_USER@$REMOTE_HOST 'nohup java -jar /bot/service-client-0.0.1-SNAPSHOT.jar > /bot/bot.log 2>&1 &'
