CREATE TABLE photos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        product_portion_id BIGINT NOT NULL,
                        photo_url VARCHAR(255) NOT NULL,
                        FOREIGN KEY (product_portion_id) REFERENCES product_portions(id) ON DELETE CASCADE
);

ALTER TABLE photos ADD CONSTRAINT unique_photo_url UNIQUE (photo_url);
CREATE INDEX idx_photos_photo_url ON photos (photo_url);

ALTER TABLE product_portions DROP COLUMN photo_url;