-- Create the tokens table
CREATE TABLE tokens (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        value VARCHAR(255) NOT NULL,
                        expired_time BIGINT NOT NULL,
                        token_type VARCHAR(50) NOT NULL,
                        CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create an index on the user_id column to optimize lookups
CREATE INDEX idx_user_id ON tokens(user_id);

