env: dev
host: #DEVHOST
resources:
  backend:
    requests:
      cpu: "0.4"
      memory:  "1Gi"
    limits:
      memory: "4Gi"
      cpu: "1"
backend:
  envs:
    SERVER_PORT: 8080
    #SPRING_DATASOURCE_URL: "jdbc:postgresql://:5432/"
    #SPRING_DATASOURCE_USERNAME: ""
    #SPRING_DATASOURCE_PASSWORD: ""
    #EMAIL_SERVICE-HOST: "http://:8080"

