name: Deploy to Server

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install
        # or for Gradle
        # run: ./gradlew build

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "service-client/target/service-client-0.0.1-SNAPSHOT.jar"  # Adjust path based on your project structure
          target: "bot/service-client-0.0.1-SNAPSHOT.jar"

      - name: Execute SSH command
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /bot
            pkill -f 'java -jar service-client-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar service-client-0.0.1-SNAPSHOT.jar > bot.log 2>&1 &